# Documentation: https://wiki.unvanquished.net/wiki/Continuous_integration

branches:
  except:
    - debian

environment:
  matrix:
    # see 96d5c1f3ed77b09c64ce7c3c7cbd37c70456b3db
    # for NMake template
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      generator: Visual Studio 16 2019
      platform: x64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      generator: Visual Studio 16 2019
      platform: win32

build:
  parallel: true

before_build:
  - git submodule update --init --recursive

build_script:
  # simple line break: space
  # double line break: line break
  - cmd: >
      cmake --version

      :: These env vars *prepend* to CMAKE_<lang>_FLAGS rather than overwriting.
      :: /Wv pins warnings to a specific compiler version so that new ones
      :: don't make the build error after Appveyor updates the compiler.

      set CFLAGS=/Wv:19.29.30037

      set CXXFLAGS=/Wv:19.29.30037

      cmake
      -Wdev -Wdeprecated
      -G"%generator%" -A"%platform%"
      -DUSE_PRECOMPILED_HEADER=0 -DUSE_WERROR=1 -DBE_VERBOSE=1
      -DBUILD_DUMMY_APP=1 -DBUILD_TESTS=1
      -S. -Bbuild

      cmake --build build --config Release

      build\Release\test-dummyapp -pakpath pkg
